// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'a90a1a32ab59808a4661c3a471483e70e5de932086f3c322f53eba955a5deb7d'>;
export type ExecutionHash =
  ExecutionHashBase<'c524fc693f115f3349a95cd3fa8ac2f9a97f38fe82bf1741ee7aa544c97b750f'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Cpu: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly brand: CodecTypes['pg/text@1']['output'];
      readonly model: CodecTypes['pg/text@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'];
      readonly socket: CodecTypes['pg/text@1']['output'];
      readonly cores: CodecTypes['pg/int4@1']['output'];
      readonly threads: CodecTypes['pg/int4@1']['output'];
      readonly baseClockGHz: CodecTypes['pg/float4@1']['output'] | null;
      readonly boostClockGHz: CodecTypes['pg/float4@1']['output'] | null;
      readonly powerDrawWatts: CodecTypes['pg/int4@1']['output'] | null;
      readonly overallScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly gamingScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly productivityScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly passmarkScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly nanoreviewScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Gpu: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly brand: CodecTypes['pg/text@1']['output'];
      readonly model: CodecTypes['pg/text@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'];
      readonly vramGB: CodecTypes['pg/int4@1']['output'];
      readonly memoryType: CodecTypes['pg/text@1']['output'] | null;
      readonly powerDrawWatts: CodecTypes['pg/int4@1']['output'] | null;
      readonly recommendedPsuWatts: CodecTypes['pg/int4@1']['output'] | null;
      readonly overallScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly gamingScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly productivityScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly passmarkScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly nanoreviewScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Cpu: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly brand: CodecTypes['pg/text@1']['input'];
      readonly model: CodecTypes['pg/text@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'];
      readonly socket: CodecTypes['pg/text@1']['input'];
      readonly cores: CodecTypes['pg/int4@1']['input'];
      readonly threads: CodecTypes['pg/int4@1']['input'];
      readonly baseClockGHz: CodecTypes['pg/float4@1']['input'] | null;
      readonly boostClockGHz: CodecTypes['pg/float4@1']['input'] | null;
      readonly powerDrawWatts: CodecTypes['pg/int4@1']['input'] | null;
      readonly overallScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly gamingScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly productivityScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly passmarkScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly nanoreviewScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Gpu: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly brand: CodecTypes['pg/text@1']['input'];
      readonly model: CodecTypes['pg/text@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'];
      readonly vramGB: CodecTypes['pg/int4@1']['input'];
      readonly memoryType: CodecTypes['pg/text@1']['input'] | null;
      readonly powerDrawWatts: CodecTypes['pg/int4@1']['input'] | null;
      readonly recommendedPsuWatts: CodecTypes['pg/int4@1']['input'] | null;
      readonly overallScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly gamingScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly productivityScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly passmarkScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly nanoreviewScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly cpu: {
      readonly baseClockGHz: CodecTypes['pg/float4@1']['output'] | null;
      readonly boostClockGHz: CodecTypes['pg/float4@1']['output'] | null;
      readonly brand: CodecTypes['pg/text@1']['output'];
      readonly cores: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'];
      readonly gamingScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly model: CodecTypes['pg/text@1']['output'];
      readonly nanoreviewScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly overallScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly passmarkScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly powerDrawWatts: CodecTypes['pg/int4@1']['output'] | null;
      readonly productivityScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly socket: CodecTypes['pg/text@1']['output'];
      readonly threads: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly gpu: {
      readonly brand: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'];
      readonly gamingScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly memoryType: CodecTypes['pg/text@1']['output'] | null;
      readonly model: CodecTypes['pg/text@1']['output'];
      readonly nanoreviewScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly overallScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly passmarkScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly powerDrawWatts: CodecTypes['pg/int4@1']['output'] | null;
      readonly productivityScore: CodecTypes['pg/float4@1']['output'] | null;
      readonly recommendedPsuWatts: CodecTypes['pg/int4@1']['output'] | null;
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly vramGB: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly cpu: {
      readonly baseClockGHz: CodecTypes['pg/float4@1']['input'] | null;
      readonly boostClockGHz: CodecTypes['pg/float4@1']['input'] | null;
      readonly brand: CodecTypes['pg/text@1']['input'];
      readonly cores: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'];
      readonly gamingScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly model: CodecTypes['pg/text@1']['input'];
      readonly nanoreviewScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly overallScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly passmarkScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly powerDrawWatts: CodecTypes['pg/int4@1']['input'] | null;
      readonly productivityScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly socket: CodecTypes['pg/text@1']['input'];
      readonly threads: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly gpu: {
      readonly brand: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'];
      readonly gamingScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly memoryType: CodecTypes['pg/text@1']['input'] | null;
      readonly model: CodecTypes['pg/text@1']['input'];
      readonly nanoreviewScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly overallScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly passmarkScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly powerDrawWatts: CodecTypes['pg/int4@1']['input'] | null;
      readonly productivityScore: CodecTypes['pg/float4@1']['input'] | null;
      readonly recommendedPsuWatts: CodecTypes['pg/int4@1']['input'] | null;
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly vramGB: CodecTypes['pg/int4@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Cpu = {
    id: CodecTypes['pg/text@1']['output'];
    slug: CodecTypes['pg/text@1']['output'];
    brand: CodecTypes['pg/text@1']['output'];
    model: CodecTypes['pg/text@1']['output'];
    fullName: CodecTypes['pg/text@1']['output'];
    socket: CodecTypes['pg/text@1']['output'];
    cores: CodecTypes['pg/int4@1']['output'];
    threads: CodecTypes['pg/int4@1']['output'];
    baseClockGHz: CodecTypes['pg/float4@1']['output'] | null;
    boostClockGHz: CodecTypes['pg/float4@1']['output'] | null;
    powerDrawWatts: CodecTypes['pg/int4@1']['output'] | null;
    overallScore: CodecTypes['pg/float4@1']['output'] | null;
    gamingScore: CodecTypes['pg/float4@1']['output'] | null;
    productivityScore: CodecTypes['pg/float4@1']['output'] | null;
    passmarkScore: CodecTypes['pg/float4@1']['output'] | null;
    nanoreviewScore: CodecTypes['pg/float4@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Gpu = {
    id: CodecTypes['pg/text@1']['output'];
    slug: CodecTypes['pg/text@1']['output'];
    brand: CodecTypes['pg/text@1']['output'];
    model: CodecTypes['pg/text@1']['output'];
    fullName: CodecTypes['pg/text@1']['output'];
    vramGB: CodecTypes['pg/int4@1']['output'];
    memoryType: CodecTypes['pg/text@1']['output'] | null;
    powerDrawWatts: CodecTypes['pg/int4@1']['output'] | null;
    recommendedPsuWatts: CodecTypes['pg/int4@1']['output'] | null;
    overallScore: CodecTypes['pg/float4@1']['output'] | null;
    gamingScore: CodecTypes['pg/float4@1']['output'] | null;
    productivityScore: CodecTypes['pg/float4@1']['output'] | null;
    passmarkScore: CodecTypes['pg/float4@1']['output'] | null;
    nanoreviewScore: CodecTypes['pg/float4@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    Cpu: Models.public_Cpu;
    Gpu: Models.public_Gpu;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly cpu: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly brand: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly model: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fullName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly socket: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cores: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly threads: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly baseClockGHz: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly boostClockGHz: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly powerDrawWatts: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly overallScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly gamingScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly productivityScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly passmarkScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly nanoreviewScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['slug'] }];
              indexes: readonly [
                {
                  readonly name: 'cpu_brand_idx_13825d71';
                  readonly prefix: 'cpu_brand_idx';
                  readonly columns: readonly ['brand'];
                  readonly unique: false;
                },
                {
                  readonly name: 'cpu_socket_idx_3d450190';
                  readonly prefix: 'cpu_socket_idx';
                  readonly columns: readonly ['socket'];
                  readonly unique: false;
                },
                {
                  readonly name: 'cpu_fullName_idx_08c13ff8';
                  readonly prefix: 'cpu_fullName_idx';
                  readonly columns: readonly ['fullName'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly gpu: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly brand: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly model: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fullName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly vramGB: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly memoryType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly powerDrawWatts: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly recommendedPsuWatts: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly overallScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly gamingScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly productivityScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly passmarkScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly nanoreviewScore: {
                  readonly nativeType: 'float4';
                  readonly codecId: 'pg/float4@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['slug'] }];
              indexes: readonly [
                {
                  readonly name: 'gpu_brand_idx_13825d71';
                  readonly prefix: 'gpu_brand_idx';
                  readonly columns: readonly ['brand'];
                  readonly unique: false;
                },
                {
                  readonly name: 'gpu_fullName_idx_08c13ff8';
                  readonly prefix: 'gpu_fullName_idx';
                  readonly columns: readonly ['fullName'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly cpu: { readonly namespace: 'public' & NamespaceId; readonly model: 'Cpu' };
    readonly gpu: { readonly namespace: 'public' & NamespaceId; readonly model: 'Gpu' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Cpu: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly brand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly model: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fullName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly socket: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cores: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly threads: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly baseClockGHz: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly boostClockGHz: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly powerDrawWatts: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly overallScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly gamingScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly productivityScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly passmarkScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly nanoreviewScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'cpu';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly slug: { readonly column: 'slug' };
                readonly brand: { readonly column: 'brand' };
                readonly model: { readonly column: 'model' };
                readonly fullName: { readonly column: 'fullName' };
                readonly socket: { readonly column: 'socket' };
                readonly cores: { readonly column: 'cores' };
                readonly threads: { readonly column: 'threads' };
                readonly baseClockGHz: { readonly column: 'baseClockGHz' };
                readonly boostClockGHz: { readonly column: 'boostClockGHz' };
                readonly powerDrawWatts: { readonly column: 'powerDrawWatts' };
                readonly overallScore: { readonly column: 'overallScore' };
                readonly gamingScore: { readonly column: 'gamingScore' };
                readonly productivityScore: { readonly column: 'productivityScore' };
                readonly passmarkScore: { readonly column: 'passmarkScore' };
                readonly nanoreviewScore: { readonly column: 'nanoreviewScore' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Gpu: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly brand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly model: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fullName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly vramGB: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly memoryType: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly powerDrawWatts: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly recommendedPsuWatts: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly overallScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly gamingScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly productivityScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly passmarkScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly nanoreviewScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'gpu';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly slug: { readonly column: 'slug' };
                readonly brand: { readonly column: 'brand' };
                readonly model: { readonly column: 'model' };
                readonly fullName: { readonly column: 'fullName' };
                readonly vramGB: { readonly column: 'vramGB' };
                readonly memoryType: { readonly column: 'memoryType' };
                readonly powerDrawWatts: { readonly column: 'powerDrawWatts' };
                readonly recommendedPsuWatts: { readonly column: 'recommendedPsuWatts' };
                readonly overallScore: { readonly column: 'overallScore' };
                readonly gamingScore: { readonly column: 'gamingScore' };
                readonly productivityScore: { readonly column: 'productivityScore' };
                readonly passmarkScore: { readonly column: 'passmarkScore' };
                readonly nanoreviewScore: { readonly column: 'nanoreviewScore' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'cpu';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'cuid2' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'cpu';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'gpu';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'cuid2' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'gpu';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
